# Generated by Django 3.2.14 on 2022-07-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img2', models.ImageField(upload_to='pics')),
                ('name2', models.CharField(max_length=250)),
                ('desc2', models.TextField()),
            ],
        ),
    ]
